version: '3.8'

services:

  client:
    build:
      context: ./path-to-your-client-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  
  server:
    build:
      context: ./path-to-your-server-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
